import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import { useRecoilState } from "recoil";
import NavOptionState from "../atoms/NavOptionsState";
import AnimatedPeople from "../components/AnimatedPeople";
import FaceBubble from "../components/FaceBubble";
import Navbar from "../components/Navbar";
import NavOptions from "../components/NavOptions";
import ProfileContainer from "../components/ProfileContainer";
import styles from "../styles/Home.module.css";

const scrollToTop = () => {
  window.scrollTo({
    top: document.body.scrollHeight,
    behavior: "smooth",
  });
};

const Home: NextPage = () => {
  const [bubbleDistance, setBubbleDistance] = useState("[0vh]");
  const [optionsHidden, setOptionsHidden] = useRecoilState(NavOptionState);
  const numBubbles = [
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
    22, 23, 24, 25, 26, 27, 28, 29, 30,
  ];
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <main className="w-screen h-screen bg-[url('/newGlobe.jpg')] z-30  "> */}
      <main className="w-screen h-screen   ">
        <div className="bg-[#59D6F6]  text-[#0F3649] w-screen h-[5vh] flex items-center justify-center ">
          UNITED VOICES OF THE WORLD
        </div>
        <div className="h-[95vh] z-0  w-screen absolute">
          <img
            src={"/newGlobe.jpg"}
            className="opacity-[0.8] object-cover w-[100%] h-[100%]"
          />
        </div>
        <section className="w-screen h-[35vh] z-40  flex-col flex items-center gap-y-10">
          <div className="text-[#59D6F6] z-40 flex flex-col justify-start items-center ">
            <span className="text-[80px]">STORIES</span>
            <span className="text-[40px]">OF OUR PEOPLE</span>
          </div>
          <>
            {numBubbles.map((bubble) => (
              <FaceBubble imgLink="https://www.incimages.com/uploaded_files/image/1920x1080/getty_624206636_200013332000928034_376810.jpg" />
            ))}
          </>
          <button
            onClick={() => scrollToTop()}
            className="border-[1px] rounded-sm border-[#59D6F6] w-[196px] h-[68px] text-[20px] text-[#59D6F6] z-40 font-sans font-thin hover:bg-[#59D6F6] hover:text-black"
          >
            Explore
          </button>
        </section>
      </main>

      <section className="w-screen h-screen">
        <Navbar />
        {!optionsHidden ? <NavOptions /> : null}
        <ProfileContainer />
      </section>
    </div>
  );
};

export default Home;
