import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/Navbar";
import ProfileContainer from "../components/ProfileContainer";
import styles from "../styles/Home.module.css";

const scrollToTop = () => {
  window.scrollTo({
    top: document.body.scrollHeight,
    behavior: "smooth",
  });
};

const Home: NextPage = () => {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-screen h-screen ">
        <div className="bg-gray-500 w-screen h-[5vh] flex items-center justify-center text-gray-300">
          United Voices of The World
        </div>
        <section className="w-screen h-[35vh]  flex-col flex items-center gap-y-10">
          <div className="flex flex-col justify-start items-center ">
            <span className="text-[80px]">STORIES</span>
            <span className="text-[40px]">OF OUR PEOPLE</span>
          </div>

          <button
            onClick={() => scrollToTop()}
            className="border-[5px] rounded-lg border-black w-[196px] h-[68px] text-[20px] hover:bg-red-300 hover:text-black"
          >
            Explore
          </button>
        </section>
        <section className="w-screen h-[60vh] flex items-center justify-center ">
          <Image className="" src="/globe.svg" width={400} height={400} />
        </section>
      </main>

      <section className="w-screen h-screen">
        <Navbar />
        <ProfileContainer />
      </section>
    </div>
  );
};

export default Home;
